config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :users
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
resources :resumes

  get 'welcome/index'

root 'welcome#index'
 resources :products 
  resources :categories

 
get "/overview", :to => "products#overview"
get "/client", :to => "products#client"
get "/warranty_policy", :to => "products#warranty_policy"
get "/order_management", :to => "customers#order_management"
get "/aboutus", :to => "products#aboutus"
get "/service", :to => "contacts#service"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @products= Product.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @products= Product.all
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
UserMailer.welcome_email(@customer).deliver
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :company, :phone, :email, :quaries)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :quaries %><br>
    <%= f.text_field :quaries %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_slider.html.erb
<ul class="bxslider" i>
<% @products.each do |i| %>
<% for image in i.images %>
<li><%= image_tag image.image.url %></li>
<% end %>
<% end %>

</ul>
<script >

$('.bxslider').bxSlider({
   slideWidth: 300,
    minSlides: 2,
    maxSlides: 3,
    startSlide: 2,
  ticker: true,
  speed: 30000
});
</script>
</ul><marquee bgcolor="litegreen" style="position: relative; left: -5px; padding: 7px; top: -94px; width: 866px;">SPECILIST IN DEFENCE AND AROSPACE ISO 9001:2008 AND AS9100:2009</marquee>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<%= render :partial => "slider" %>

<div class="img-right">
 <%= image_tag("F18-a.gif", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%>
 </div>
<h5>CUSTOMER SUPPORT</h5>

Please place your complaints either through the website or address your complaints by fax or postal mail to:

<h5>PARK CONTROLS & COMMUNICATIONS LTD.,<br>
22, 80 FEET ROAD, HAL 3RD STAGE<br>
BANGALORE 560 075</h5>
<h5>PHONE:</h5>.  +91 80 2529 3482 / 2529 2513 / 2529 7199
<h5>FAX:</h5>  +91 80 2528 1716
<h5>EMAIL:</h5>  info@parkcontrols.com<br>
For complaints through our website fill up the following:

<p id="notice"><%= notice %></p>

<h1> Customers</h1>
<table class="table table-bordered table-striped">

  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
     
      <th>Phone</th>
      <th>Email</th>
      
      <th>Quaries</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.company %></td>
    
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
       
        <td><%= customer.quaries %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>
<style>
  div.img-right{
     float:right;


  }


</style>

app/views/customers/new.html.erb
<%= render :partial => "slider" %>

<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @customer.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Quaries:</strong>
  <%= @customer.quaries %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>