config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :users
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
resources :resumes

  get 'welcome/index'

root 'welcome#index'
 resources :products 
  resources :categories

 
get "/overview", :to => "products#overview"
get "/client", :to => "products#client"
get "/warranty_policy", :to => "products#warranty_policy"
get "/order_management", :to => "customers#order_management"
get "/aboutus", :to => "products#aboutus"
get "/service", :to => "contacts#service"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    @products= Product.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @products= Product.all
  end
def service
  @products= Product.all
end
  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :address)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_slider.html.erb
<ul class="bxslider" i>
<% @products.each do |i| %>
<% for image in i.images %>
<li><%= image_tag image.image.url %></li>
<% end %>
<% end %>

</ul>
<script >

$('.bxslider').bxSlider({
   slideWidth: 300,
    minSlides: 2,
    maxSlides: 3,
    startSlide: 2,
  ticker: true,
  speed: 30000
});
</script>
</ul><marquee bgcolor="litegreen" style="position: relative; left: -5px; padding: 7px; top: -94px; width: 866px;">SPECILIST IN DEFENCE AND AROSPACE ISO 9001:2008 AND AS9100:2009</marquee>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<%= render :partial => "slider" %>

<div class="img-right">
 <%= image_tag("LAPTOP (1).jpg", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%>
 </div>
<h5>CONTACT US</h5>

<h5>Corporate Office</h5>

Park Controls & Communications Pvt Ltd.,<br>

Kishan Arcade<br>
NO 464, 465, 466, New Thippasandra Main Road, HAL 3rd Stage<br>
Bangalore - 560 075, India<h5>
<h5>Phone Number & Email</h5>
Phone : +91-80-2529 2513 / 2529 7199 / 2529 3482<br>
Fax : 91-80-2528 1716 / 4091 0252<br>
Email : info@parkcontrols.com
<p id="notice"><%= notice %></p>


<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>
<table class="table table-bordered table-striped">

  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
<style>
   div.img-right{
     float: right;
   }
  </style>

app/views/contacts/new.html.erb
<%= render :partial => "slider" %>
<div class="img-right">
 <%= image_tag("LAPTOP (1).jpg", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%>
 </div>
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>
<style>
   div.img-right{
     float: right;
   }
  </style>

app/views/contacts/service.html.erb
<%= render :partial => "slider" %>
<h5>SERVICES</h5>
 
  <%= image_tag("soft_1.gif", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%><br>
 <%= image_tag("test_eqip.gif", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%>
Park Controls & Communications Ltd., extends design and maintenance services. The services provided are comprehensive for a variety of Applications and the nature of these services pertain to:

	<h5>» Engineering Design</h5>
	<h5>» Automatic Test Equipment</h5>
	<h5>» Maintenance Services</h5>

<h5>ENGINEERING DESIGN</h5>

Park Controls & Communications Ltd., has extensive hardware and software design experience in the areas of End to End Data Acquisition, Digital communication systems, Control systems, Test systems, etc. using various families of micro-controllers, digital signal processors and FPGA devices.<br><br>


Park Controls' hardware design experience encompasses DSP design, FPGA design, and board design for applications in the areas of End to End Data Acquisition for Airborne and Ground Applications, digital communications, timing, telemetry, etc.<br><br>


Park Controls has excellent experience in designing, developing and testing real-time data acquisition and processing software for Telemetry, embedded software for digital communication systems and software for Automatic Test Systems.<br><br>

Park Controls follows rigorous quality control procedures during the development life cycle and employs standards like DOD 2167A, MIL 498 and IEEE 12207 for their software development.<br><br>

Park Controls' undertakes and services turnkey jobs from concept to implementation; total system design and implementation starting from specifications, as well as offering specific services related to an individual area of expertise.<br>

<h5>Software Services:</h5>

	• Platform based Application Development<br>
	• Software Tool Development<br>
	• Software Porting<br>
	• Embedded Application Development<br>
	• Firmware Development<br>
	• Device Drivers

<h5>Hardware Services:</h5>

	• PCB Design Services<br>
	• FPGA Design services<br>
	• DSP Design services<br>
	• Product Engineering services<br><br>

The company has extensive facilities both in house and outsourced to productionize and supply the designed and developed products and systems in quantities.

          



<style>
	img.img-right{
    float: right;


	}

</style>.

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>