config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :users
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
resources :resumes

  get 'welcome/index'

root 'welcome#index'
 resources :products 
  resources :categories

 
get "/overview", :to => "products#overview"
get "/client", :to => "products#client"
get "/warranty_policy", :to => "products#warranty_policy"
get "/order_management", :to => "customers#order_management"
get "/aboutus", :to => "products#aboutus"
get "/service", :to => "contacts#service"
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :images, :as => :imagable
	belongs_to :category
	accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if=>:all_blank
has_attached_file :image, styles: { medium: "100x100>", thumb: "100x100>"  }
def self.search(search)
  if search
 where('name LIKE ?', "%#{search}%")
   else
    all
  end
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	if params[:category].blank?
@products=Product.all.order("created_at ASC")

else
@category_id = Category.find_by(:name=>params[:category]).id
@products = Product.where(category_id: @category_id).order("created_at DESC")
end

	#	@products= Product.search(params[:search])
	end

	def new
    @product = Product.new
1.times{@product.images.build}

end

def create
    @product = Product.new(product_params)
 1.times{@product.images.build} if @product.images.blank?
 if @product.save
  redirect_to products_path
    flash[:notice] = "Successfully created product."
else
  render :new
  end
end
	 def show
	 	@product= Product.find(params[:id])
 
	 end

	 def edit
	 	@product= Product.find(params[:id])
	 end

	 def update
	 	@product= Product.find(params[:id])
	 	if @product.update(product_params)
	 		redirect_to products_path
	 		  flash[:notice] = "Successfully updated product."
	 	else
	 		render "edit"
	 	end
	 end

	 def destroy
	 	@product= Product.find(params[:id])
	 	@product.destroy
	 	redirect_to products_path
	 	  flash[:notice] = "Successfully destroy product."
	 end
def listing
    	@product= Product.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
def overview
	@products= Product.all
end

 def warranty_policy
 	@products= Product.all
 end

def client
	@products= Product.all
end
def aboutus
	@products= Product.all
end
	 private

	 def product_params
	 	params.require(:product).permit!
	 end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= nested_form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.select(:category_id, Category.all.map {|c| [c.name, c.id]}, :prompt =>"Choose a Category")%>
  </div>
<div>
<%= f.fields_for :images do |image| %>
  <%= image.file_field :image %>
  <%= image.link_to_remove "Remove image" %>
<% end %>
<p><%= f.link_to_add "Add a image", :images %></p>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div><br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div><br>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </table>
<% end %>
 </table>

app/views/products/_product_show.html.erb
_product_show.html.erb

app/views/products/_slider.html.erb
<ul class="bxslider" i>
<% @products.each do |i| %>
<% for image in i.images %>
<li><%= image_tag image.image.url %></li>
<% end %>
<% end %>

</ul>
<script >

$('.bxslider').bxSlider({
   slideWidth: 300,
    minSlides: 2,
    maxSlides: 3,
    startSlide: 2,
  ticker: true,
  speed: 30000
});
</script>
</ul><marquee bgcolor="litegreen" style="position: relative; left: -5px; padding: 7px; top: -94px; width: 866px;">SPECILIST IN DEFENCE AND AROSPACE ISO 9001:2008 AND AS9100:2009</marquee>

app/views/products/aboutus.html.erb
<%= render :partial => "slider" %>
<div class="img-right">
   <%= image_tag("aboutus.gif", alt: "File Name Fancy", :class=>"img-right", size: "2150*2150")%>
</div>
<h5>ABOUT US</h5>
Park Controls & Communications Ltd., services the very unique customized technology intensive needs of customers who include DRDO labs and ranges, ISRO Labs and ranges, Defence Services, Defence Avionics OEMs, etc.

The company operates out of their fully equipped facility in the city of Bangalore, India with good quality infrastructure that includes design and test tools and manpower that is a cut above the rest.
<br>
The company enjoys the following Accreditations:

	»<h5> »Approved R&D Unit under the Ministry of Science & Technology</h5>
	<h5>» ISO 9001:2000 certified by UL Inc</h5>
	
	• Design & Development, Manufacture, Installation and Servicing of Electronic System Products such as Telemetry, Timing and Automated Test Equipment
	<br>
	• Provision of Software for the Design and Development of Electronics System Products
	<br>

	<h5>» CEMILAC – (Centre for Military Airworthiness & Certification) approved for undertaking design, development and supply of Airborne LRUs</h5>
	
	• Design of Electronic System LRUs using embedded / DSP technologies for Telemetry, Timing, Radar, Avionics, etc.
	<br>
	• Electronic Design Services for Airborne Equipment
	<br>
	<h5>» AS9100, Rev B certified by DSQ-UL</h5>

	
	• The Design, Development, Manufacture, Installation and Servicing of Telemetry and Timing Equipments, Automated Test Equipments and Airborne Data Acquisition modules for Defence and Aerospace applications
	<br>
	• The Design & Development of Distributed Data Acquisition, Monitoring and Processing
	<br>
	• Software for Aerospace and Defence applications

	<h5>» Defense Offset Facilitation Agency recognized company</h5>
	<h5>» Registered with EHTP - Electronics Hardware Tech. Park</h5>

The company's offering of products and services include the following areas of specialization:

	<h5>» End to End Data Acquisition products and systems for all applications particularly for</h5>
	
	• Telemetry<br>
	• Timing<br>
	• Control

	<h5>» Automated Test Equipments for</h5>
	
	• Defence and Avionics LRUs<br>
	• Ground Checkout Systems<br>
	• Large cluster of UUTs
	<h5>» Engineering Services for</h5>
	
	• System / Product design<br>
	• Legacy Upgrade of products / systems<br>
	• Form, Fit & Function replacement

	<h5>» Maintenance Services for</h5>
	
	• System Level trouble shooting<br>
	• Third party /OEM supplied systems and products<br>
	• Maintenance Services on behalf of OEMs

The company services Indian and overseas clients with in depth skills in Embedded Systems design and development.
	<h5>---------------------------2015.....................</h5>

<style>
   div.img-right{
     float: right;

   }
</style>

app/views/products/client.html.erb
<%= render :partial => "slider" %>
<div class="img-right">
 <%= image_tag("our_clients.jpg", alt: "File Name Fancy", size: "2150*2150")%>
 </div>
<h5>CLIENTS</h5>

Park Controls & Communications Ltd., enjoys the confidence of very esteemed user groups within the Indian Defence R&D labs, Ranges and Services and also within the Indian Space Research Organization.<br>

The company has successfully met with every customer’s specific requirements through product offerings that precisely fit into the user expectations.<br>

Product Engineering services have resulted in customized and indigenized solutions. Many products and systems that hitherto have been imported are provided with indigenous alternatives enabling the Indian Defence and Space programs move closer to self dependence for technologies once considered the forte of company outside India.<br><br>

Our partial list of satisfied customers includes:

<h6>Indian Space Research Organisation (ISRO), Telemetry, Tracking & Command Network (ISTRAC)</h6>

Telemetry Modules<br>
Timing Modules<br>
<h6>Vikram Sarabhai Space Center</h6>
Telemetry Modules<br>
Timing Modules<br>
<h6>ISRO Satellite Center</h6>
Telemetry System<br>
<h6>Space Applications Center</h6>
Telemetry Modules<br>
<h6>Satish Dhawan Space Center (SHAR)</h6>
Timing Modules<br>
Antenna Control Units<br>
Master Control Facility<br>
Telemetry Modules<br>
Timing Modules<br>
<h6>Liquid Propulsion Systems Centre</h6>
Timing Modules<br>
<h6>Aeronautical Development Agency</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules
<h6>Integrated Test Range</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Systems<br>
Antenna Control Units
<h6>Defence Research & Development Laboratory</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules
<h6>Research Center Imarat</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules
<h6>Hindustan Aeronautics Limited</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules<br>
Automated Test Benches
<h6>Bharat Electronics Limited</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules
<h6>Electronics Corporation of India Limited</h6>
Time Reference Systems<br>
<h6>Central Scientific Instruments Organization</h6>
Head Up Display Test Bench<br>
<h6>Software Development Institute</h6>
INS Test Bench<br>
HUDWAC Promming Station
<h6>National Aerospace Laboratories</h6>
Telemetry Data Acquisition and Processing Station<br>
Generic Data Acquisition Modules
<h6>Aircraft & Systems Testing Establishment (ASTE)</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
<h6>Aeronautical Development Establishment</h6>
Comprehensive Telemetry Data Acquisition and Processing Station<br>
Timing Modules
<h6>Electronics & Radar Development Establishment<
Timing Modules
 <style>
   div.img-right{
     float: right;
   }
  </style>

app/views/products/edit.html.erb
<h1>Editing Product</h1>


<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render :partial => "slider" %>
 <%= form_tag products_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<h1>Listing Products</h1>

<table>
  <thead>
  <tr>
      <th>No</th>
      <th>Name</th>
      <th>Dis</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
  </thead>
  <tbody>
  </tbody>
  </tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.category_id %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %>
      
        <% product.images.each do |image| %>
<td><%= image_tag image.image %></td>
<% end %>
</td>
        <td>
       <%= link_to "show",product_path(product.id) %>

      <%= link_to "edit", edit_product_path(product.id)  %>  
      <%= link_to "delete", product_path(product.id), method: :delete, data: { confirm: 'Are you sure?' }  %>
      </td>
   
    </tr>
</div>  
</tbody>

<% end %>

</table>

<%= link_to 'New Product', new_product_path %>

app/views/products/listing.js.erb
$("#product_show").html('<%= escape_javascript render :partial => '/products/product_show' %>');

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/overview.html.erb
<%= render :partial => "slider" %>
<h5>Overview</h5>
Park Controls & Communications Ltd., specializes in supporting products that are Industrial, MIL and Airworthiness certified.<br>

The product portfolio includes those that are used for:<br>

<h6>•	End to End Data Acquisition Solutions</h6>
<h6>•	PCM Telemetry Solutions</h6>
<h6>•	Timing Solutions</h6>
<h6>•	Control Solutions</h6>
<h6>•	Test Benches for any Avionics LRU</h6>

The products can be supplied as individual items are integrated into a total system which warrants the use of third party products to realize the final system on a turn key basis.<br><br>

Park Controls & Communications Ltd., also specializes in product engineering wherein the customer specifies the concept and the final realization of the product rests with the company.<br><br>

The company follows the International Development Life Cycle procedures and maintains strict adherence to Quality and Time line issues.<br>

The Design so realized and approved by the customer can also be undertaken for production of the product evolved in quantities.

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
<% @product.images.each do |i| %>
<%= image_tag i.image %>
<% end %>
</p>

</p>

<p>
  <%= @product.description %>
</p>
<%= link_to "View Details", new_user_session_path() %>

app/views/products/warranty_policy.html.erb
<%= render :partial => "slider" %>
<h5>WARRANTY POLICY</h5>

<h6>The Warranty on the system / card/ unit supplied is subject to the following conditions:</h6>

WARRANTY STANDS VOID IN CASE OF ANY PHYSICAL DAMAGE TO THE SYSTEM/CARD/UNIT SUPPLIED OR ANY ATTEMPT MADE TO OPEN THE DELIVERED SYSTEM/CARD/UNIT IN THE ABSENCE OF COMPANY ENGINEER RENDERING THE SYSTEM SUPPLIED NON-FUNCTIONAL AT THE CUSTOMER PLACE.<br>

WARRANTY STANDS VOID IF ANY SYSTEM/CARD/UNIT IS BURNT OR IS MADE NON-FUNCTIONAL DUE TO ELECTRICAL PROBLEMS LIKE SHOCK/ POWER SURGE/ FIRE AT THE CUSTOMER SITE.<br>

WARRANTY STANDS VOID IF THE DELIVERED AND ACCEPTED SYSTEM/CARD/UNIT IS REPAIRED WITHOUT PRIOR INFORMATION TO AND APPROVAL FROM PARK CONTROLS IN WRITING OR IF ANY UNAUTHORIZED PERSON/COMPANY MAKES AN ATTEMPT TO SERVICE THE SAME.<br>

WARRANTY STANDS VOID IF THE SYSTEM/CARD/UNIT SUPPLIED IS USED IN A MANNER OTHER THAN THAT SPECIFIED IN THE ACCEPTANCE TEST REPORT THAT WOULD MAKE THE SYSTEM NON FUNCTIONAL.<br>

WARRANTY STANDS VOID IF THE SYSTEM/CARD/UNIT IS FOUND DAMAGED DUE TO INTERFACING WITH OTHER SYSTEMS WITHOUT PRIOR INFORMATION TO AND APPROVAL FROM PARK CONTROLS IN WRITING
WARRANTY STANDS VOID IF THE SERIAL NO AND MANUFACTURER SEAL IS BROKEN OR IS REMOVED.<br>

<h5>CUSTOMER COMPLAINT PROCEDURE</h5>

The system/card/unit supplied to each customer has undergone extensive tests and procedural care has been taken to ensure superior quality. However in the unlikely event of a failure of the system/card/unit supplied the customer is requested to follow the procedure given below for speedy attention of any complaint.<br>

1)	Complaints in written form indicating the date and specific problem(s) faced are to be addressed to Customer Support Department. It is easier to keep track of complaint when lodged in writing to the Customer Support Department.<br>

2)	A written acknowledgement is sent to every written complaint.<br>

3)	In case of complaints that are to be placed orally such complaints are received by the front office during office hours and every complaint is registered the front office.<br>

4)	For all complaints a compliant registration number is furnished to the person placing the complaint. This number has to be referred in all correspondence and enquiries regarding this complaint.<br>

5)	The complaint will be attended to, within 24 hours in case of installations within Bangalore and 48 to 72 hours in case of installations outside Bangalore.<br>

6)	All efforts will be made to rectify the fault at the earliest possible time period.