config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :customers
  devise_for :users
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
resources :resumes

  get 'welcome/index'

root 'welcome#index'
 resources :products 
  resources :categories

 
get "/overview", :to => "products#overview"
get "/client", :to => "products#client"
get "/warranty_policy", :to => "products#warranty_policy"
get "/order_management", :to => "customers#order_management"
get "/aboutus", :to => "products#aboutus"
get "/service", :to => "contacts#service"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Park" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<% if current_user %>

          <li><%= link_to "Log out ", destroy_user_session_path, :method => :delete  %></li>
<% else %>
   <% end %>
   <%= image_tag("logo12.gif", alt: "File Name Fancy", size: "2150*2150")%>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home',  welcome_index_path %></li>
             <li><%= link_to 'About Us', aboutus_path %></li>
    <li><%= link_to 'Services', service_path %></li>

      <li>
             <div id = "account" class=" dropdown">
                        <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                            <span>Products</span> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu pull-right">
                             <li>  <%= link_to 'Overview', overview_path %> </li>              
                        
                          <% Category.all.each do |category| %>
<li><%= link_to category.name,  products_path(:category => category.name) %></li>
<% end %>
    <li><%= link_to 'Waranty policy', warranty_policy_path %></li>
                        </ul>
                </div>
              </li>
               <li><%= link_to 'customer support', customers_path %></li>
 <li><%= link_to "Career@Park", resumes_path %></li>
  <li><%= link_to 'Contact Us', contacts_path %></li>
   <li><%= link_to 'Clients', client_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
            <ul class="nav nav-list">
             
           <div class="well sidebar-nav">
            Search our database to find information about any products and technical documents of Park Controls and Communications.
              <ul class="nav nav-list">
                <li class="nav-header"</li>
              <p id="notice"><%= notice %></p>
<%= form_tag products_path, :id => 'search_form', :method => :get do %>
Search: <%= select_tag :category, options_for_select([["Select Products",""]]+Category.all.map{|a| a.name}) %>
<% end %>
<script>
  $('#category').change(function()
 {
     $('#search_form').submit();
 });
</script>

            </div><!--/.well -->
          
          </div><!--/span-->
        </div><!--/row-->
       
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>